version: '3.8'

services:
  # 1. AWS DynamoDB yerine: DynamoDB Local
  local-dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: link-shortener-local-dynamodb
    user: root
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"

  # 2. AWS ElastiCache yerine: Redis Alpine
  local-redis:
    image: redis:alpine
    container_name: link-shortener-local-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  local-postgres:
    image: postgres:16-alpine
    container_name: linkshortener-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_DB=linkshortener_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  dynamodb_data:
  redis_data:
  postgres_data: