name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ] # main branch'ine push yapıldı��nda �al���r

jobs:
  # test:
  #   name: Run Integration Tests (Testcontainers)
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Code
  #     uses: actions/checkout@v4

  #   - name: Setup .NET 9
  #     uses: actions/setup-dotnet@v4
  #     with:
  #       dotnet-version: '9.0.x'
  
  build-and-push:
    name: Build & Push to Docker Hub and Update GitOps
    runs-on: ubuntu-latest
    
    steps:
    # 1. Kodu GitHub runner'a çekiyoruz
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Docker Hub'a giriş yapıyoruz
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 3. Docker imajını build edip Docker Hub'a pushluyoruz (Tag olarak Commit SHA kullanıyoruz)
    - name: Build and push Docker image
      id: build-image
      env:
        IMAGE_NAME: mcysrdckr/link_shortener
        IMAGE_TAG: ${{ github.sha }} # Commit SHA'sını tag olarak kullanıyoruz
      run: |
        # LinkShortener.API projesinin Dockerfile'ını kullanarak imajı oluştur
        docker build -t $IMAGE_NAME:$IMAGE_TAG -f Dockerfile .
        docker push $IMAGE_NAME:$IMAGE_TAG
        echo "image=$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_OUTPUT

    # 4. GitOps reposundaki imaj tag'ini güncelliyoruz (CD Tetikleme)
    - name: Update GitOps Manifest
      env:
        GITOPS_TOKEN: ${{ secrets.GITOPS_PAT }} # GitOps reposuna erişim için PAT
        IMAGE_FULL_NAME: mcysrdckr/link_shortener # Docker Hub'daki tam imaj adı
        IMAGE_TAG: ${{ github.sha }} # Yeni imaj tag'i
      run: |
        # GitOps reposunu geçici olarak klonluyoruz
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git clone https://${{ env.GITOPS_TOKEN }}@github.com/${{ github.repository_owner }}/link-shortener-gitops.git
        cd link-shortener-gitops/environments/local/app-resources
        
        # Kustomize dosyasındaki imaj adını ve tag'ini güncelliyoruz
        # newName: mcysrdckr/link_shortener
        # newTag: <commit-sha>
        sed -i "s|newName: .*|newName: ${IMAGE_FULL_NAME}|g" kustomization.yaml
        sed -i "s|newTag: .*|newTag: ${IMAGE_TAG}|g" kustomization.yaml
        
        # Değişiklikleri GitOps reposuna pushluyoruz
        git add kustomization.yaml
        git commit -m "chore: update backend image tag to ${IMAGE_TAG} [skip ci]" # [skip ci] ile bu commit'in tekrar CI tetiklemesini önleriz
        git push origin main